# SPACESHIP

SPACESHIP_AWS_SHOW=true
SPACESHIP_AWS_PREFIX=''
SPACESHIP_GIT_SHOW=true
SPACESHIP_GIT_PREFIX=''
SPACESHIP_GIT_STATUS_PREFIX='['
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_PREFIX=''
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_VENV_SHOW=true
SPACESHIP_VENV_PREFIX=''
SPACESHIP_VENV_SYMBOL="🐍"

export REPORTTIME=10